<a href="https://colab.research.google.com/github/shashankkanthula/Python-basics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

In [49]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [50]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


**Creating Arrays**

In [51]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

# to check the dimensions
print(arr.ndim)

# 0-D Array
import numpy as np
arr = np.array(42)
print(arr)

#1-D Array
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(arr.ndim)

#2-D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

#3-D Array
import numpy as np
arr = np.array([[[7,8,9],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)


[1 2 3 4]
<class 'numpy.ndarray'>
1
42
[1 2 3 4]
1
[[1 2 3]
 [4 5 6]]
[[[7 8 9]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**Array Indexing**

In [52]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[2] + arr[3])

#Accessing 2-D Array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])
print(arr[1,4])

#Accessing 3-D Array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

#Negative Indexing
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])
#

1
7
2
10
6
10


**Array Slicing**

In [53]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])

#Negative slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

#step
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

#Slicing 2-D Array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


**Numpy Data Types**

In [54]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

import numpy as np
arr=np.array(['apple','banana'])
print(arr.dtype)

import numpy as np
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

int64
<U6
[b'1' b'2' b'3' b'4']
|S1


**Copy vs View**

In [55]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

y=arr.view()
print(arr)
print(y)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


**Array Shape**

In [56]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array:',arr.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


**Array Reshape**

In [57]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
newarr=arr.reshape(3,3)
print(newarr)

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr.reshape(2,5,1)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
